# Spring Boot 应用配置
server:
  port: 8080
  servlet:
    context-path: /api
  tomcat:
    uri-encoding: UTF-8
    threads:
      max: 200
      min-spare: 10
    max-connections: 10000
    max-http-post-size: 104857600  # 100MB

# Spring 配置
spring:
  application:
    name: hospital-report-system
  profiles:
    active: dev
    include: ai
  
  # 数据源配置
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hospital_report_system?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: ganwanli
    hikari:
      pool-name: HikariCP-Primary
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 30000
      max-lifetime: 900000
      connection-timeout: 30000
      connection-test-query: SELECT 1
      leak-detection-threshold: 60000

  # Redis配置
  redis:
    host: localhost
    port: 6379
    password: 
    timeout: 5000ms
    lettuce:
      pool:
        max-active: 20
        max-wait: -1ms
        max-idle: 10
        min-idle: 5
      shutdown-timeout: 100ms
    database: 0

  # JSON配置
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      write-dates-as-timestamps: false
      write-null-map-values: false
      fail-on-empty-beans: false
    deserialization:
      fail-on-unknown-properties: false
    default-property-inclusion: NON_NULL

  # 文件上传配置
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 100MB
      file-size-threshold: 0

  # JPA配置（用于自动建表）
  jpa:
    hibernate:
      ddl-auto: update  # 自动更新表结构
    show-sql: true      # 显示SQL语句
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: true # 格式化SQL语句
        use_sql_comments: true # 添加SQL注释

# MyBatis Plus配置
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.hospital.report.entity
  global-config:
    db-config:
      id-type: AUTO
      table-underline: true
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
      update-strategy: NOT_NULL
      select-strategy: NOT_EMPTY
    banner: false
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
    call-setters-on-nulls: true
    jdbc-type-for-null: NULL
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# JWT配置
jwt:
  secret: hospitalReportSystemSecretKey2024ForJWTTokenGeneration
  expiration: 7200000  # 2小时，单位毫秒
  header: Authorization
  prefix: "Bearer "
  refresh-expiration: 604800000  # 7天，单位毫秒

# 日志配置
logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
    com.hospital.report.config: DEBUG
    com.hospital.report.security: DEBUG
    com.hospital.report: DEBUG
    com.hospital.report.mapper: DEBUG
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n'
    file: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n'
  file:
    name: logs/hospital-report-system.log
    max-size: 100MB
    max-history: 30

# Swagger配置
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  packages-to-scan: com.hospital.report.controller
  paths-to-match: /**

# 应用自定义配置
app:
  # 安全配置
  security:
    # 忽略认证的URL
    ignore-urls:
      urls:
      - /auth/login
      - /auth/logout
      - /auth/refresh
      - /swagger-ui/**
      - /v3/api-docs/**
      - /swagger-ui.html
      - /swagger-resources/**
      - /webjars/**
      - /actuator/**
      - /druid/**
      - /system/dict/**
      - /datasource/**
      - /sql-execution/**
      - /sql-templates/**
      - /ai-assistant/**
      - /ai-schema/**
    # 跨域配置
    cors:
      allowed-origins: 
        - http://localhost:3000
        - http://127.0.0.1:3000
        - http://localhost:3001
        - http://127.0.0.1:3001
        - http://localhost:5173
        - http://127.0.0.1:5173
      allowed-methods: 
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      allowed-headers: "*"
      allow-credentials: true
      max-age: 3600

  # 文件存储配置
  file:
    upload-path: /opt/hospital-report/uploads
    max-size: 10485760  # 10MB
    allowed-types:
      - .jpg
      - .jpeg
      - .png
      - .gif
      - .pdf
      - .doc
      - .docx
      - .xls
      - .xlsx

# 管理端点配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when-authorized
  metrics:
    export:
      prometheus:
        enabled: true