# 开发环境配置
spring:
  # 数据源配置
  datasource:
    primary:
      url: jdbc:mysql://localhost:3306/hospital_report_system?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 123456
      hikari:
        pool-name: HikariCP-Primary-Dev
        minimum-idle: 5
        maximum-pool-size: 20

  # Redis配置
  redis:
    host: localhost
    port: 6379
    password: 
    database: 0

# JWT配置
jwt:
  secret: hospitalReportSystemDevSecretKey2024
  expiration: 7200000  # 2小时

# 日志配置
logging:
  level:
    root: INFO
    com.hospital.report: DEBUG
    com.hospital.report.mapper: DEBUG
    org.springframework.security: DEBUG
    org.apache.ibatis: DEBUG
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n'

# MyBatis Plus配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    banner: true

# Swagger配置
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

# 应用自定义配置
app:
  # 多数据源配置
  datasource:
    dynamic:
      enabled: true
      datasource:
        master:
          url: jdbc:mysql://localhost:3306/hospital_report_system?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
          username: root
          password: 123456
        slave:
          url: jdbc:mysql://localhost:3306/hospital_report_system?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
          username: root
          password: 123456

  # 安全配置
  security:
    cors:
      allowed-origins: 
        - http://localhost:3000
        - http://127.0.0.1:3000
        - http://localhost:5173
        - http://127.0.0.1:5173
        - http://localhost:8081
        - http://127.0.0.1:8081

  # 文件存储配置
  file:
    upload-path: ./uploads
    max-size: 10485760

# 开发工具配置
debug: false