-- 数据血缘节点表
CREATE TABLE IF NOT EXISTS `lineage_node` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `node_id` varchar(100) NOT NULL COMMENT '节点ID（唯一标识）',
  `node_type` varchar(50) NOT NULL COMMENT '节点类型（TABLE/COLUMN/VIEW/PROCEDURE等）',
  `node_name` varchar(200) NOT NULL COMMENT '节点名称',
  `display_name` varchar(200) DEFAULT NULL COMMENT '显示名称',
  `node_category` varchar(50) DEFAULT NULL COMMENT '节点分类',
  `database_name` varchar(100) DEFAULT NULL COMMENT '数据库名',
  `schema_name` varchar(100) DEFAULT NULL COMMENT '模式名',
  `table_name` varchar(100) DEFAULT NULL COMMENT '表名',
  `column_name` varchar(100) DEFAULT NULL COMMENT '字段名',
  `data_type` varchar(50) DEFAULT NULL COMMENT '数据类型',
  `business_meaning` text COMMENT '业务含义',
  `technical_description` text COMMENT '技术描述',
  `owner_user` varchar(100) DEFAULT NULL COMMENT '责任人',
  `owner_department` varchar(100) DEFAULT NULL COMMENT '责任部门',
  `system_source` varchar(100) DEFAULT NULL COMMENT '系统来源',
  `environment` varchar(50) DEFAULT NULL COMMENT '环境（DEV/TEST/PROD）',
  `node_properties` text COMMENT '节点属性（JSON格式）',
  `position_x` double DEFAULT NULL COMMENT 'X坐标',
  `position_y` double DEFAULT NULL COMMENT 'Y坐标',
  `node_level` int(11) DEFAULT NULL COMMENT '节点层级',
  `criticality_level` varchar(20) DEFAULT NULL COMMENT '重要性级别（LOW/MEDIUM/HIGH/CRITICAL）',
  `sensitivity_level` varchar(20) DEFAULT NULL COMMENT '敏感性级别',
  `data_classification` varchar(20) DEFAULT NULL COMMENT '数据分类',
  `usage_frequency` varchar(20) DEFAULT NULL COMMENT '使用频率',
  `last_access_time` datetime DEFAULT NULL COMMENT '最后访问时间',
  `data_quality_score` double DEFAULT NULL COMMENT '数据质量分数',
  `status` int(11) DEFAULT 1 COMMENT '状态（0-禁用，1-启用）',
  `created_by` bigint(20) DEFAULT NULL COMMENT '创建人',
  `created_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` bigint(20) DEFAULT NULL COMMENT '更新人',
  `updated_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `is_deleted` tinyint(1) DEFAULT 0 COMMENT '是否删除（0-否，1-是）',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_node_id` (`node_id`),
  KEY `idx_node_type` (`node_type`),
  KEY `idx_table_name` (`table_name`),
  KEY `idx_system_source` (`system_source`),
  KEY `idx_created_time` (`created_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='数据血缘节点表';

-- 数据血缘关系表
CREATE TABLE IF NOT EXISTS `data_lineage` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `source_id` varchar(100) NOT NULL COMMENT '源节点ID',
  `target_id` varchar(100) NOT NULL COMMENT '目标节点ID',
  `source_name` varchar(200) DEFAULT NULL COMMENT '源节点名称',
  `target_name` varchar(200) DEFAULT NULL COMMENT '目标节点名称',
  `source_type` varchar(50) DEFAULT NULL COMMENT '源节点类型',
  `target_type` varchar(50) DEFAULT NULL COMMENT '目标节点类型',
  `source_table` varchar(100) DEFAULT NULL COMMENT '源表名',
  `target_table` varchar(100) DEFAULT NULL COMMENT '目标表名',
  `relation_type` varchar(50) NOT NULL COMMENT '关系类型（DERIVED/TRANSFORM/COPY等）',
  `transform_rule` text COMMENT '转换规则',
  `business_context` text COMMENT '业务上下文',
  `data_flow_direction` varchar(20) DEFAULT 'DOWNSTREAM' COMMENT '数据流向',
  `dependency_level` int(11) DEFAULT NULL COMMENT '依赖层级',
  `confidence_score` double DEFAULT 0.8 COMMENT '置信度分数（0-1）',
  `discovery_method` varchar(50) DEFAULT NULL COMMENT '发现方法（MANUAL/AUTO/SCAN等）',
  `verification_status` varchar(20) DEFAULT 'UNVERIFIED' COMMENT '验证状态',
  `last_verified_time` datetime DEFAULT NULL COMMENT '最后验证时间',
  `lineage_strength` varchar(20) DEFAULT NULL COMMENT '血缘强度',
  `impact_weight` double DEFAULT NULL COMMENT '影响权重',
  `metadata` text COMMENT '元数据（JSON格式）',
  `status` int(11) DEFAULT 1 COMMENT '状态（0-禁用，1-启用）',
  `created_by` bigint(20) DEFAULT NULL COMMENT '创建人',
  `created_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` bigint(20) DEFAULT NULL COMMENT '更新人',
  `updated_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `is_deleted` tinyint(1) DEFAULT 0 COMMENT '是否删除（0-否，1-是）',
  PRIMARY KEY (`id`),
  KEY `idx_source_id` (`source_id`),
  KEY `idx_target_id` (`target_id`),
  KEY `idx_relation_type` (`relation_type`),
  KEY `idx_created_time` (`created_time`),
  KEY `idx_source_target` (`source_id`, `target_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='数据血缘关系表';

-- 血缘影响分析表
CREATE TABLE IF NOT EXISTS `lineage_impact_analysis` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `analysis_id` varchar(100) NOT NULL COMMENT '分析ID',
  `source_node_id` varchar(100) NOT NULL COMMENT '源节点ID',
  `impact_type` varchar(50) NOT NULL COMMENT '影响类型（UPDATE/DELETE/SCHEMA_CHANGE等）',
  `impact_level` varchar(20) DEFAULT NULL COMMENT '影响级别（LOW/MEDIUM/HIGH/CRITICAL）',
  `impact_scope` text COMMENT '影响范围',
  `impact_probability` double DEFAULT NULL COMMENT '影响概率',
  `risk_level` varchar(20) DEFAULT NULL COMMENT '风险级别',
  `affected_objects` text COMMENT '受影响对象（JSON格式）',
  `recommendations` text COMMENT '建议措施（JSON格式）',
  `analysis_method` varchar(50) DEFAULT NULL COMMENT '分析方法',
  `analysis_depth` int(11) DEFAULT NULL COMMENT '分析深度',
  `execution_time` bigint(20) DEFAULT NULL COMMENT '执行时间（毫秒）',
  `analysis_result` text COMMENT '分析结果（JSON格式）',
  `status` int(11) DEFAULT 1 COMMENT '状态（0-禁用，1-启用）',
  `created_by` bigint(20) DEFAULT NULL COMMENT '创建人',
  `created_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` bigint(20) DEFAULT NULL COMMENT '更新人',
  `updated_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `is_deleted` tinyint(1) DEFAULT 0 COMMENT '是否删除（0-否，1-是）',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_analysis_id` (`analysis_id`),
  KEY `idx_source_node_id` (`source_node_id`),
  KEY `idx_impact_type` (`impact_type`),
  KEY `idx_created_time` (`created_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='血缘影响分析表';

-- 数据字典表
CREATE TABLE IF NOT EXISTS `data_dictionary` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `field_code` varchar(100) NOT NULL COMMENT '字段编码',
  `field_name` varchar(200) NOT NULL COMMENT '字段名称',
  `field_name_en` varchar(200) DEFAULT NULL COMMENT '英文名称',
  `data_type` varchar(50) NOT NULL COMMENT '数据类型',
  `field_length` int(11) DEFAULT NULL COMMENT '字段长度',
  `decimal_places` int(11) DEFAULT NULL COMMENT '小数位数',
  `is_nullable` tinyint(1) DEFAULT 1 COMMENT '是否允许空值',
  `default_value` varchar(500) DEFAULT NULL COMMENT '默认值',
  `business_meaning` text COMMENT '业务含义',
  `technical_description` text COMMENT '技术描述',
  `value_range` varchar(500) DEFAULT NULL COMMENT '取值范围',
  `example_values` varchar(500) DEFAULT NULL COMMENT '示例值',
  `data_source` varchar(100) DEFAULT NULL COMMENT '数据来源',
  `update_frequency` varchar(50) DEFAULT NULL COMMENT '更新频率',
  `quality_rules` text COMMENT '质量规则',
  `category_id` bigint(20) DEFAULT NULL COMMENT '分类ID',
  `category_name` varchar(100) DEFAULT NULL COMMENT '分类名称',
  `standard_code` varchar(100) DEFAULT NULL COMMENT '标准编码',
  `version` varchar(20) DEFAULT '1.0' COMMENT '版本号',
  `status` int(11) DEFAULT 1 COMMENT '状态（0-草稿，1-发布，2-废弃）',
  `created_by` bigint(20) DEFAULT NULL COMMENT '创建人',
  `created_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` bigint(20) DEFAULT NULL COMMENT '更新人',
  `updated_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `is_deleted` tinyint(1) DEFAULT 0 COMMENT '是否删除（0-否，1-是）',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_field_code` (`field_code`),
  KEY `idx_field_name` (`field_name`),
  KEY `idx_category_id` (`category_id`),
  KEY `idx_data_type` (`data_type`),
  KEY `idx_created_time` (`created_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='数据字典表';

-- 用户表（简化版本）
CREATE TABLE IF NOT EXISTS `sys_user` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '用户ID',
  `username` varchar(30) NOT NULL COMMENT '用户账号',
  `password` varchar(100) DEFAULT '' COMMENT '密码',
  `nickname` varchar(30) NOT NULL COMMENT '用户昵称',
  `email` varchar(50) DEFAULT '' COMMENT '用户邮箱',
  `phone` varchar(11) DEFAULT '' COMMENT '手机号码',
  `sex` char(1) DEFAULT '0' COMMENT '用户性别（0男 1女 2未知）',
  `avatar` varchar(100) DEFAULT '' COMMENT '头像地址',
  `status` char(1) DEFAULT '0' COMMENT '帐号状态（0正常 1停用）',
  `dept_id` bigint(20) DEFAULT NULL COMMENT '部门ID',
  `login_ip` varchar(128) DEFAULT '' COMMENT '最后登录IP',
  `login_date` datetime DEFAULT NULL COMMENT '最后登录时间',
  `created_by` bigint(20) DEFAULT NULL COMMENT '创建者',
  `created_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` bigint(20) DEFAULT NULL COMMENT '更新者',
  `updated_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `is_deleted` tinyint(1) DEFAULT 0 COMMENT '删除标志（0代表存在 1代表删除）',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_username` (`username`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='用户信息表';

-- 插入默认管理员用户（密码：admin123）
INSERT INTO `sys_user` (`username`, `password`, `nickname`, `email`, `phone`, `status`) 
VALUES ('admin', '$2a$10$7JB720yubVSOfvzKGGDVHOu0RuJm9rIKSSVv4Xzd8Xxv5f4.CFCG2', '系统管理员', 'admin@hospital.com', '13800138000', '0')
ON DUPLICATE KEY UPDATE `nickname` = '系统管理员';